version: '3.9'

services:

  app:
    build: ..
    volumes:
      - ./project/:/code/project/
    environment:
      FLASK_APP: "app.py"
      FLASK_ENV: 'development'
    command: flask run -h 0.0.0.0 -p 5000
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
